env:
    browser: true
    es6: true
extends:
    - "eslint:recommended"
    - plugin:import/errors
    - plugin:import/warnings
plugins:
    - import
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaVersion: 2018
    sourceType: module
rules:
    import/no-unresolved: [2, { commonjs: true, amd: true }]
    import/named: 2
    import/namespace: 2
    import/default: 2
    import/export: 2
